### ISSUE TITLE
Platen can't build on Hugo `0.120.4` - SCSS error due to malformed function returns

### ISSUE THREAD

**Issue by santagoy** [platenio/platen#101]
CONTEXT: I installed platen my following the guide in the readme about referencing it in my hugo.toml file and updating the modules. I then want to build the site but I keep getting the error detailed below.

Whenever I try to build a site using the command `hugo server --minify` I instead get an error that tells me the following:

`Error: error building site: TOCSS: failed to transform "platen.scss" (text/x-scss):`

It then lists my directory to my Hugo cache with a message detailing the specific error that follows: `@import directive requires a url or quoted path`

I read somewhere that `@import` is being deprecated in favor of `@use` in SCSS and SASS. Maybe there's an issue with the way a number of partials are referenced? Thank you and I hope to hear from someone about this soon!

**Comment by michaeltlombardi** [comment]
Hi! I cloned your repository and built your site from `main` (santagoy/san-tagoy-xyz@d6a25d829505dfdb780c111a1b3ef5a5cf394208) - without errors for SCSS. Are you having trouble working from a specific branch?

**Comment by santagoy** [comment]
I am rebuilding the site from scratch in a different repo in a different branch!

Will link it my following reply

**Comment by santagoy** [comment]
https://github.com/santagoy/san-tagoy-neoc/tree/nu-platen

**Comment by michaeltlombardi** [comment]
Ran the issue down. The problem is that starting in Hugo `1.20.0`, the return value for the style utility functions, which returns delimited strings, is being converted to HTML (and thereby escaped) before being inserted into the SCSS.

Instead of this:

https://github.com/platenio/platen/blob/3451ed7a46af938ec302e115709f9ea291824d87/modules/platen/layouts/partials/platen/utils/styles/import.html#L15

We should have:

```html
{{- $renderStrings = delimit $renderStrings "\n" | safeCSS -}}
{{- return $renderStrings -}}
```
